//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 5.0.61118.0
// 
namespace MentorJWcfService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblUserInfo", Namespace="http://schemas.datacontract.org/2004/07/MentorJWcfService")]
    public partial class tblUserInfo : object
    {
        
        private System.DateTime AccountCreationDateField;
        
        private System.Nullable<bool> AccountLockedField;
        
        private System.Nullable<int> AgeField;
        
        private System.Nullable<System.DateTime> BirthdayField;
        
        private string CityField;
        
        private string CountryField;
        
        private string EmailField;
        
        private System.Nullable<long> FailedLoginAttemptsField;
        
        private string First_NameField;
        
        private byte[] LastActiveDateField;
        
        private System.Nullable<System.DateTime> LastFailedLoginDateField;
        
        private System.DateTime LastLoginDateField;
        
        private System.DateTime LastUpdatedDateField;
        
        private string Last_NameField;
        
        private string Middle_NameField;
        
        private string PasswordField;
        
        private string PhoneNumberField;
        
        private string SexField;
        
        private string StateField;
        
        private string Street_AddressField;
        
        private long UserIDField;
        
        private string UserNameField;
        
        private string ZipCodeField;
        
        private System.Nullable<bool> isAdminField;
        
        private System.Nullable<bool> isMentorField;
        
        private System.Nullable<bool> isPremiumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AccountCreationDate
        {
            get
            {
                return this.AccountCreationDateField;
            }
            set
            {
                this.AccountCreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> AccountLocked
        {
            get
            {
                return this.AccountLockedField;
            }
            set
            {
                this.AccountLockedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Age
        {
            get
            {
                return this.AgeField;
            }
            set
            {
                this.AgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Birthday
        {
            get
            {
                return this.BirthdayField;
            }
            set
            {
                this.BirthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> FailedLoginAttempts
        {
            get
            {
                return this.FailedLoginAttemptsField;
            }
            set
            {
                this.FailedLoginAttemptsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name
        {
            get
            {
                return this.First_NameField;
            }
            set
            {
                this.First_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] LastActiveDate
        {
            get
            {
                return this.LastActiveDateField;
            }
            set
            {
                this.LastActiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastFailedLoginDate
        {
            get
            {
                return this.LastFailedLoginDateField;
            }
            set
            {
                this.LastFailedLoginDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastLoginDate
        {
            get
            {
                return this.LastLoginDateField;
            }
            set
            {
                this.LastLoginDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedDate
        {
            get
            {
                return this.LastUpdatedDateField;
            }
            set
            {
                this.LastUpdatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_Name
        {
            get
            {
                return this.Last_NameField;
            }
            set
            {
                this.Last_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Middle_Name
        {
            get
            {
                return this.Middle_NameField;
            }
            set
            {
                this.Middle_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex
        {
            get
            {
                return this.SexField;
            }
            set
            {
                this.SexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street_Address
        {
            get
            {
                return this.Street_AddressField;
            }
            set
            {
                this.Street_AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> isAdmin
        {
            get
            {
                return this.isAdminField;
            }
            set
            {
                this.isAdminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> isMentor
        {
            get
            {
                return this.isMentorField;
            }
            set
            {
                this.isMentorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> isPremium
        {
            get
            {
                return this.isPremiumField;
            }
            set
            {
                this.isPremiumField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMentorJService")]
public interface IMentorJService
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMentorJService/ReadRecord", ReplyAction="http://tempuri.org/IMentorJService/ReadRecordResponse")]
    System.IAsyncResult BeginReadRecord(long ID, System.AsyncCallback callback, object asyncState);
    
    MentorJWcfService.tblUserInfo EndReadRecord(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMentorJService/AddUpdateRecord", ReplyAction="http://tempuri.org/IMentorJService/AddUpdateRecordResponse")]
    System.IAsyncResult BeginAddUpdateRecord(MentorJWcfService.tblUserInfo rec, System.AsyncCallback callback, object asyncState);
    
    bool EndAddUpdateRecord(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMentorJService/InsertRecord", ReplyAction="http://tempuri.org/IMentorJService/InsertRecordResponse")]
    System.IAsyncResult BeginInsertRecord(MentorJWcfService.tblUserInfo rec, System.AsyncCallback callback, object asyncState);
    
    bool EndInsertRecord(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMentorJService/DeleteRecord", ReplyAction="http://tempuri.org/IMentorJService/DeleteRecordResponse")]
    System.IAsyncResult BeginDeleteRecord(long ID, System.AsyncCallback callback, object asyncState);
    
    bool EndDeleteRecord(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMentorJService/UpdateRecord", ReplyAction="http://tempuri.org/IMentorJService/UpdateRecordResponse")]
    System.IAsyncResult BeginUpdateRecord(MentorJWcfService.tblUserInfo rec, System.AsyncCallback callback, object asyncState);
    
    bool EndUpdateRecord(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMentorJService/ValidateLogin", ReplyAction="http://tempuri.org/IMentorJService/ValidateLoginResponse")]
    System.IAsyncResult BeginValidateLogin(string username, string password, System.AsyncCallback callback, object asyncState);
    
    MentorJWcfService.tblUserInfo EndValidateLogin(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMentorJService/checkLoginName", ReplyAction="http://tempuri.org/IMentorJService/checkLoginNameResponse")]
    System.IAsyncResult BegincheckLoginName(MentorJWcfService.tblUserInfo rec, System.AsyncCallback callback, object asyncState);
    
    bool EndcheckLoginName(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMentorJServiceChannel : IMentorJService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ReadRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public ReadRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public MentorJWcfService.tblUserInfo Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((MentorJWcfService.tblUserInfo)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AddUpdateRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public AddUpdateRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public bool Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class InsertRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public InsertRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public bool Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DeleteRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public DeleteRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public bool Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UpdateRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public UpdateRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public bool Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ValidateLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public ValidateLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public MentorJWcfService.tblUserInfo Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((MentorJWcfService.tblUserInfo)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class checkLoginNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public checkLoginNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public bool Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MentorJServiceClient : System.ServiceModel.ClientBase<IMentorJService>, IMentorJService
{
    
    private BeginOperationDelegate onBeginReadRecordDelegate;
    
    private EndOperationDelegate onEndReadRecordDelegate;
    
    private System.Threading.SendOrPostCallback onReadRecordCompletedDelegate;
    
    private BeginOperationDelegate onBeginAddUpdateRecordDelegate;
    
    private EndOperationDelegate onEndAddUpdateRecordDelegate;
    
    private System.Threading.SendOrPostCallback onAddUpdateRecordCompletedDelegate;
    
    private BeginOperationDelegate onBeginInsertRecordDelegate;
    
    private EndOperationDelegate onEndInsertRecordDelegate;
    
    private System.Threading.SendOrPostCallback onInsertRecordCompletedDelegate;
    
    private BeginOperationDelegate onBeginDeleteRecordDelegate;
    
    private EndOperationDelegate onEndDeleteRecordDelegate;
    
    private System.Threading.SendOrPostCallback onDeleteRecordCompletedDelegate;
    
    private BeginOperationDelegate onBeginUpdateRecordDelegate;
    
    private EndOperationDelegate onEndUpdateRecordDelegate;
    
    private System.Threading.SendOrPostCallback onUpdateRecordCompletedDelegate;
    
    private BeginOperationDelegate onBeginValidateLoginDelegate;
    
    private EndOperationDelegate onEndValidateLoginDelegate;
    
    private System.Threading.SendOrPostCallback onValidateLoginCompletedDelegate;
    
    private BeginOperationDelegate onBegincheckLoginNameDelegate;
    
    private EndOperationDelegate onEndcheckLoginNameDelegate;
    
    private System.Threading.SendOrPostCallback oncheckLoginNameCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public MentorJServiceClient()
    {
    }
    
    public MentorJServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MentorJServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MentorJServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MentorJServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<ReadRecordCompletedEventArgs> ReadRecordCompleted;
    
    public event System.EventHandler<AddUpdateRecordCompletedEventArgs> AddUpdateRecordCompleted;
    
    public event System.EventHandler<InsertRecordCompletedEventArgs> InsertRecordCompleted;
    
    public event System.EventHandler<DeleteRecordCompletedEventArgs> DeleteRecordCompleted;
    
    public event System.EventHandler<UpdateRecordCompletedEventArgs> UpdateRecordCompleted;
    
    public event System.EventHandler<ValidateLoginCompletedEventArgs> ValidateLoginCompleted;
    
    public event System.EventHandler<checkLoginNameCompletedEventArgs> checkLoginNameCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMentorJService.BeginReadRecord(long ID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginReadRecord(ID, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    MentorJWcfService.tblUserInfo IMentorJService.EndReadRecord(System.IAsyncResult result)
    {
        return base.Channel.EndReadRecord(result);
    }
    
    private System.IAsyncResult OnBeginReadRecord(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        long ID = ((long)(inValues[0]));
        return ((IMentorJService)(this)).BeginReadRecord(ID, callback, asyncState);
    }
    
    private object[] OnEndReadRecord(System.IAsyncResult result)
    {
        MentorJWcfService.tblUserInfo retVal = ((IMentorJService)(this)).EndReadRecord(result);
        return new object[] {
                retVal};
    }
    
    private void OnReadRecordCompleted(object state)
    {
        if ((this.ReadRecordCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.ReadRecordCompleted(this, new ReadRecordCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void ReadRecordAsync(long ID)
    {
        this.ReadRecordAsync(ID, null);
    }
    
    public void ReadRecordAsync(long ID, object userState)
    {
        if ((this.onBeginReadRecordDelegate == null))
        {
            this.onBeginReadRecordDelegate = new BeginOperationDelegate(this.OnBeginReadRecord);
        }
        if ((this.onEndReadRecordDelegate == null))
        {
            this.onEndReadRecordDelegate = new EndOperationDelegate(this.OnEndReadRecord);
        }
        if ((this.onReadRecordCompletedDelegate == null))
        {
            this.onReadRecordCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReadRecordCompleted);
        }
        base.InvokeAsync(this.onBeginReadRecordDelegate, new object[] {
                    ID}, this.onEndReadRecordDelegate, this.onReadRecordCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMentorJService.BeginAddUpdateRecord(MentorJWcfService.tblUserInfo rec, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginAddUpdateRecord(rec, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    bool IMentorJService.EndAddUpdateRecord(System.IAsyncResult result)
    {
        return base.Channel.EndAddUpdateRecord(result);
    }
    
    private System.IAsyncResult OnBeginAddUpdateRecord(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        MentorJWcfService.tblUserInfo rec = ((MentorJWcfService.tblUserInfo)(inValues[0]));
        return ((IMentorJService)(this)).BeginAddUpdateRecord(rec, callback, asyncState);
    }
    
    private object[] OnEndAddUpdateRecord(System.IAsyncResult result)
    {
        bool retVal = ((IMentorJService)(this)).EndAddUpdateRecord(result);
        return new object[] {
                retVal};
    }
    
    private void OnAddUpdateRecordCompleted(object state)
    {
        if ((this.AddUpdateRecordCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.AddUpdateRecordCompleted(this, new AddUpdateRecordCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void AddUpdateRecordAsync(MentorJWcfService.tblUserInfo rec)
    {
        this.AddUpdateRecordAsync(rec, null);
    }
    
    public void AddUpdateRecordAsync(MentorJWcfService.tblUserInfo rec, object userState)
    {
        if ((this.onBeginAddUpdateRecordDelegate == null))
        {
            this.onBeginAddUpdateRecordDelegate = new BeginOperationDelegate(this.OnBeginAddUpdateRecord);
        }
        if ((this.onEndAddUpdateRecordDelegate == null))
        {
            this.onEndAddUpdateRecordDelegate = new EndOperationDelegate(this.OnEndAddUpdateRecord);
        }
        if ((this.onAddUpdateRecordCompletedDelegate == null))
        {
            this.onAddUpdateRecordCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddUpdateRecordCompleted);
        }
        base.InvokeAsync(this.onBeginAddUpdateRecordDelegate, new object[] {
                    rec}, this.onEndAddUpdateRecordDelegate, this.onAddUpdateRecordCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMentorJService.BeginInsertRecord(MentorJWcfService.tblUserInfo rec, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginInsertRecord(rec, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    bool IMentorJService.EndInsertRecord(System.IAsyncResult result)
    {
        return base.Channel.EndInsertRecord(result);
    }
    
    private System.IAsyncResult OnBeginInsertRecord(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        MentorJWcfService.tblUserInfo rec = ((MentorJWcfService.tblUserInfo)(inValues[0]));
        return ((IMentorJService)(this)).BeginInsertRecord(rec, callback, asyncState);
    }
    
    private object[] OnEndInsertRecord(System.IAsyncResult result)
    {
        bool retVal = ((IMentorJService)(this)).EndInsertRecord(result);
        return new object[] {
                retVal};
    }
    
    private void OnInsertRecordCompleted(object state)
    {
        if ((this.InsertRecordCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.InsertRecordCompleted(this, new InsertRecordCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void InsertRecordAsync(MentorJWcfService.tblUserInfo rec)
    {
        this.InsertRecordAsync(rec, null);
    }
    
    public void InsertRecordAsync(MentorJWcfService.tblUserInfo rec, object userState)
    {
        if ((this.onBeginInsertRecordDelegate == null))
        {
            this.onBeginInsertRecordDelegate = new BeginOperationDelegate(this.OnBeginInsertRecord);
        }
        if ((this.onEndInsertRecordDelegate == null))
        {
            this.onEndInsertRecordDelegate = new EndOperationDelegate(this.OnEndInsertRecord);
        }
        if ((this.onInsertRecordCompletedDelegate == null))
        {
            this.onInsertRecordCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertRecordCompleted);
        }
        base.InvokeAsync(this.onBeginInsertRecordDelegate, new object[] {
                    rec}, this.onEndInsertRecordDelegate, this.onInsertRecordCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMentorJService.BeginDeleteRecord(long ID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginDeleteRecord(ID, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    bool IMentorJService.EndDeleteRecord(System.IAsyncResult result)
    {
        return base.Channel.EndDeleteRecord(result);
    }
    
    private System.IAsyncResult OnBeginDeleteRecord(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        long ID = ((long)(inValues[0]));
        return ((IMentorJService)(this)).BeginDeleteRecord(ID, callback, asyncState);
    }
    
    private object[] OnEndDeleteRecord(System.IAsyncResult result)
    {
        bool retVal = ((IMentorJService)(this)).EndDeleteRecord(result);
        return new object[] {
                retVal};
    }
    
    private void OnDeleteRecordCompleted(object state)
    {
        if ((this.DeleteRecordCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.DeleteRecordCompleted(this, new DeleteRecordCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void DeleteRecordAsync(long ID)
    {
        this.DeleteRecordAsync(ID, null);
    }
    
    public void DeleteRecordAsync(long ID, object userState)
    {
        if ((this.onBeginDeleteRecordDelegate == null))
        {
            this.onBeginDeleteRecordDelegate = new BeginOperationDelegate(this.OnBeginDeleteRecord);
        }
        if ((this.onEndDeleteRecordDelegate == null))
        {
            this.onEndDeleteRecordDelegate = new EndOperationDelegate(this.OnEndDeleteRecord);
        }
        if ((this.onDeleteRecordCompletedDelegate == null))
        {
            this.onDeleteRecordCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteRecordCompleted);
        }
        base.InvokeAsync(this.onBeginDeleteRecordDelegate, new object[] {
                    ID}, this.onEndDeleteRecordDelegate, this.onDeleteRecordCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMentorJService.BeginUpdateRecord(MentorJWcfService.tblUserInfo rec, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginUpdateRecord(rec, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    bool IMentorJService.EndUpdateRecord(System.IAsyncResult result)
    {
        return base.Channel.EndUpdateRecord(result);
    }
    
    private System.IAsyncResult OnBeginUpdateRecord(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        MentorJWcfService.tblUserInfo rec = ((MentorJWcfService.tblUserInfo)(inValues[0]));
        return ((IMentorJService)(this)).BeginUpdateRecord(rec, callback, asyncState);
    }
    
    private object[] OnEndUpdateRecord(System.IAsyncResult result)
    {
        bool retVal = ((IMentorJService)(this)).EndUpdateRecord(result);
        return new object[] {
                retVal};
    }
    
    private void OnUpdateRecordCompleted(object state)
    {
        if ((this.UpdateRecordCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.UpdateRecordCompleted(this, new UpdateRecordCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void UpdateRecordAsync(MentorJWcfService.tblUserInfo rec)
    {
        this.UpdateRecordAsync(rec, null);
    }
    
    public void UpdateRecordAsync(MentorJWcfService.tblUserInfo rec, object userState)
    {
        if ((this.onBeginUpdateRecordDelegate == null))
        {
            this.onBeginUpdateRecordDelegate = new BeginOperationDelegate(this.OnBeginUpdateRecord);
        }
        if ((this.onEndUpdateRecordDelegate == null))
        {
            this.onEndUpdateRecordDelegate = new EndOperationDelegate(this.OnEndUpdateRecord);
        }
        if ((this.onUpdateRecordCompletedDelegate == null))
        {
            this.onUpdateRecordCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateRecordCompleted);
        }
        base.InvokeAsync(this.onBeginUpdateRecordDelegate, new object[] {
                    rec}, this.onEndUpdateRecordDelegate, this.onUpdateRecordCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMentorJService.BeginValidateLogin(string username, string password, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginValidateLogin(username, password, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    MentorJWcfService.tblUserInfo IMentorJService.EndValidateLogin(System.IAsyncResult result)
    {
        return base.Channel.EndValidateLogin(result);
    }
    
    private System.IAsyncResult OnBeginValidateLogin(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string username = ((string)(inValues[0]));
        string password = ((string)(inValues[1]));
        return ((IMentorJService)(this)).BeginValidateLogin(username, password, callback, asyncState);
    }
    
    private object[] OnEndValidateLogin(System.IAsyncResult result)
    {
        MentorJWcfService.tblUserInfo retVal = ((IMentorJService)(this)).EndValidateLogin(result);
        return new object[] {
                retVal};
    }
    
    private void OnValidateLoginCompleted(object state)
    {
        if ((this.ValidateLoginCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.ValidateLoginCompleted(this, new ValidateLoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void ValidateLoginAsync(string username, string password)
    {
        this.ValidateLoginAsync(username, password, null);
    }
    
    public void ValidateLoginAsync(string username, string password, object userState)
    {
        if ((this.onBeginValidateLoginDelegate == null))
        {
            this.onBeginValidateLoginDelegate = new BeginOperationDelegate(this.OnBeginValidateLogin);
        }
        if ((this.onEndValidateLoginDelegate == null))
        {
            this.onEndValidateLoginDelegate = new EndOperationDelegate(this.OnEndValidateLogin);
        }
        if ((this.onValidateLoginCompletedDelegate == null))
        {
            this.onValidateLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnValidateLoginCompleted);
        }
        base.InvokeAsync(this.onBeginValidateLoginDelegate, new object[] {
                    username,
                    password}, this.onEndValidateLoginDelegate, this.onValidateLoginCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMentorJService.BegincheckLoginName(MentorJWcfService.tblUserInfo rec, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BegincheckLoginName(rec, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    bool IMentorJService.EndcheckLoginName(System.IAsyncResult result)
    {
        return base.Channel.EndcheckLoginName(result);
    }
    
    private System.IAsyncResult OnBegincheckLoginName(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        MentorJWcfService.tblUserInfo rec = ((MentorJWcfService.tblUserInfo)(inValues[0]));
        return ((IMentorJService)(this)).BegincheckLoginName(rec, callback, asyncState);
    }
    
    private object[] OnEndcheckLoginName(System.IAsyncResult result)
    {
        bool retVal = ((IMentorJService)(this)).EndcheckLoginName(result);
        return new object[] {
                retVal};
    }
    
    private void OncheckLoginNameCompleted(object state)
    {
        if ((this.checkLoginNameCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.checkLoginNameCompleted(this, new checkLoginNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void checkLoginNameAsync(MentorJWcfService.tblUserInfo rec)
    {
        this.checkLoginNameAsync(rec, null);
    }
    
    public void checkLoginNameAsync(MentorJWcfService.tblUserInfo rec, object userState)
    {
        if ((this.onBegincheckLoginNameDelegate == null))
        {
            this.onBegincheckLoginNameDelegate = new BeginOperationDelegate(this.OnBegincheckLoginName);
        }
        if ((this.onEndcheckLoginNameDelegate == null))
        {
            this.onEndcheckLoginNameDelegate = new EndOperationDelegate(this.OnEndcheckLoginName);
        }
        if ((this.oncheckLoginNameCompletedDelegate == null))
        {
            this.oncheckLoginNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OncheckLoginNameCompleted);
        }
        base.InvokeAsync(this.onBegincheckLoginNameDelegate, new object[] {
                    rec}, this.onEndcheckLoginNameDelegate, this.oncheckLoginNameCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IMentorJService CreateChannel()
    {
        return new MentorJServiceClientChannel(this);
    }
    
    private class MentorJServiceClientChannel : ChannelBase<IMentorJService>, IMentorJService
    {
        
        public MentorJServiceClientChannel(System.ServiceModel.ClientBase<IMentorJService> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginReadRecord(long ID, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = ID;
            System.IAsyncResult _result = base.BeginInvoke("ReadRecord", _args, callback, asyncState);
            return _result;
        }
        
        public MentorJWcfService.tblUserInfo EndReadRecord(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            MentorJWcfService.tblUserInfo _result = ((MentorJWcfService.tblUserInfo)(base.EndInvoke("ReadRecord", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginAddUpdateRecord(MentorJWcfService.tblUserInfo rec, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = rec;
            System.IAsyncResult _result = base.BeginInvoke("AddUpdateRecord", _args, callback, asyncState);
            return _result;
        }
        
        public bool EndAddUpdateRecord(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            bool _result = ((bool)(base.EndInvoke("AddUpdateRecord", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginInsertRecord(MentorJWcfService.tblUserInfo rec, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = rec;
            System.IAsyncResult _result = base.BeginInvoke("InsertRecord", _args, callback, asyncState);
            return _result;
        }
        
        public bool EndInsertRecord(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            bool _result = ((bool)(base.EndInvoke("InsertRecord", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginDeleteRecord(long ID, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = ID;
            System.IAsyncResult _result = base.BeginInvoke("DeleteRecord", _args, callback, asyncState);
            return _result;
        }
        
        public bool EndDeleteRecord(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            bool _result = ((bool)(base.EndInvoke("DeleteRecord", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginUpdateRecord(MentorJWcfService.tblUserInfo rec, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = rec;
            System.IAsyncResult _result = base.BeginInvoke("UpdateRecord", _args, callback, asyncState);
            return _result;
        }
        
        public bool EndUpdateRecord(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            bool _result = ((bool)(base.EndInvoke("UpdateRecord", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginValidateLogin(string username, string password, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = username;
            _args[1] = password;
            System.IAsyncResult _result = base.BeginInvoke("ValidateLogin", _args, callback, asyncState);
            return _result;
        }
        
        public MentorJWcfService.tblUserInfo EndValidateLogin(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            MentorJWcfService.tblUserInfo _result = ((MentorJWcfService.tblUserInfo)(base.EndInvoke("ValidateLogin", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BegincheckLoginName(MentorJWcfService.tblUserInfo rec, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = rec;
            System.IAsyncResult _result = base.BeginInvoke("checkLoginName", _args, callback, asyncState);
            return _result;
        }
        
        public bool EndcheckLoginName(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            bool _result = ((bool)(base.EndInvoke("checkLoginName", _args, result)));
            return _result;
        }
    }
}
