

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MentorJWcfService
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class MentorJEntities : DbContext
{
    public MentorJEntities()
        : base("name=MentorJEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tblComment> tblComments { get; set; }

    public virtual DbSet<tblForum> tblForums { get; set; }

    public virtual DbSet<tblFriend> tblFriends { get; set; }

    public virtual DbSet<tblGroup> tblGroups { get; set; }

    public virtual DbSet<tblGroupMember> tblGroupMembers { get; set; }

    public virtual DbSet<tblPhoto> tblPhotoes { get; set; }

    public virtual DbSet<tblPhotoAlbum> tblPhotoAlbums { get; set; }

    public virtual DbSet<tblPost> tblPosts { get; set; }

    public virtual DbSet<tblUserInfo> tblUserInfoes { get; set; }

    public virtual DbSet<tblUserProfile> tblUserProfiles { get; set; }

    public virtual DbSet<tblUserSetting> tblUserSettings { get; set; }

    public virtual DbSet<tblVideo> tblVideos { get; set; }

}

}

