
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MentorJWcfService
{

using System;
    using System.Collections.Generic;
    
public partial class tblComment
{

    public long CommentID { get; set; }

    public long ParentID { get; set; }

    public long UserID { get; set; }

    public Nullable<long> PhotoID { get; set; }

    public Nullable<long> VideoID { get; set; }

    public int Likes { get; set; }

    public string Description { get; set; }

    public System.DateTime Created { get; set; }

    public System.DateTime Modified { get; set; }

}

}
