
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MentorJWcfService
{

using System;
    using System.Collections.Generic;
    
public partial class tblFriend
{

    public long UserID { get; set; }

    public long FriendID { get; set; }

}

}
