//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MentorJWcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserProfile
    {
        public long UserID { get; set; }
        public string About { get; set; }
        public string WebProfileLink { get; set; }
        public string WebPicturesOfLink { get; set; }
        public string PictureURL { get; set; }
        public string BigPictureURL { get; set; }
        public string SmallPictureURL { get; set; }
        public System.DateTime Modified { get; set; }
        public byte[] PictureData { get; set; }
    }
}
