#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MentorJ.Android.Resource", IsApplication=true)]

namespace MentorJ.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int array_months = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BackgroundGradient = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonContinueStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ButtonLogInStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int EditTextStyle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int samplelogo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int SpinnerItem = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060013
			public const int AdditionalInfo = 2131099667;
			
			// aapt resource value: 0x7f060020
			public const int BasicInfo = 2131099680;
			
			// aapt resource value: 0x7f060017
			public const int boxFemale = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int boxMale = 2131099670;
			
			// aapt resource value: 0x7f060028
			public const int btnContinue = 2131099688;
			
			// aapt resource value: 0x7f06001f
			public const int btnContinue2 = 2131099679;
			
			// aapt resource value: 0x7f060010
			public const int btn_reg_back = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int btn_reg_create = 2131099663;
			
			// aapt resource value: 0x7f06002b
			public const int btn_reg_logout = 2131099691;
			
			// aapt resource value: 0x7f060004
			public const int buttonLogin = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int editPassword = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int editUsername = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int getUserInfoButton = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int getUserInfoTextView = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int imageLogo = 2131099648;
			
			// aapt resource value: 0x7f06002a
			public const int lblDashboard = 2131099690;
			
			// aapt resource value: 0x7f060012
			public const int linearLayout1 = 2131099666;
			
			// aapt resource value: 0x7f060007
			public const int loginButton = 2131099655;
			
			// aapt resource value: 0x7f060029
			public const int mLlayoutBottomButtons = 2131099689;
			
			// aapt resource value: 0x7f060008
			public const int sayHelloWorldButton = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int sayHelloWorldTextView = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int scrollView1 = 2131099665;
			
			// aapt resource value: 0x7f060018
			public const int spinner = 2131099672;
			
			// aapt resource value: 0x7f060014
			public const int tableLayout1 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int tableRow1 = 2131099669;
			
			// aapt resource value: 0x7f060001
			public const int textCaption = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int textForgotPassword = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int textRegister = 2131099654;
			
			// aapt resource value: 0x7f06001a
			public const int txtCity = 2131099674;
			
			// aapt resource value: 0x7f060027
			public const int txtConfirmPassword = 2131099687;
			
			// aapt resource value: 0x7f06001d
			public const int txtCountry = 2131099677;
			
			// aapt resource value: 0x7f060024
			public const int txtEmail = 2131099684;
			
			// aapt resource value: 0x7f060021
			public const int txtFirstName = 2131099681;
			
			// aapt resource value: 0x7f060023
			public const int txtLastName = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int txtMiddleName = 2131099682;
			
			// aapt resource value: 0x7f060026
			public const int txtPassword = 2131099686;
			
			// aapt resource value: 0x7f06001e
			public const int txtPhoneNumber = 2131099678;
			
			// aapt resource value: 0x7f06001b
			public const int txtState = 2131099675;
			
			// aapt resource value: 0x7f060019
			public const int txtStreetAddress = 2131099673;
			
			// aapt resource value: 0x7f060025
			public const int txtUsername = 2131099685;
			
			// aapt resource value: 0x7f06001c
			public const int txtZipcode = 2131099676;
			
			// aapt resource value: 0x7f06000d
			public const int txt_reg_email = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int txt_reg_password = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int txt_reg_username = 2131099660;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Register = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RegisterAdditionalInfo = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RegisterBasicInfo = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Storyboard = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040005
			public const int ApplicationName = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int get_UserInfo = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int get_hello_world_data = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int login = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int month_prompt = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int say_hello_world = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
