#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MentorJ.Android.Resource", IsApplication=true)]

namespace MentorJ.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int array_months = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BackgroundGradient = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonContinueStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ButtonLogInStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int EditTextStyle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_overflow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int samplelogo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int SpinnerItem = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int xs = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080022
			public const int AdditionalInfo = 2131230754;
			
			// aapt resource value: 0x7f08002f
			public const int BasicInfo = 2131230767;
			
			// aapt resource value: 0x7f080026
			public const int boxFemale = 2131230758;
			
			// aapt resource value: 0x7f080025
			public const int boxMale = 2131230757;
			
			// aapt resource value: 0x7f080037
			public const int btnContinue = 2131230775;
			
			// aapt resource value: 0x7f08002e
			public const int btnContinue2 = 2131230766;
			
			// aapt resource value: 0x7f08000c
			public const int btnForgotPw = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int btnLogin = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public const int btnRegister = 2131230733;
			
			// aapt resource value: 0x7f080003
			public const int btnReturn = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int btnSample = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int btnSend = 2131230722;
			
			// aapt resource value: 0x7f08001f
			public const int btn_reg_back = 2131230751;
			
			// aapt resource value: 0x7f08001e
			public const int btn_reg_create = 2131230750;
			
			// aapt resource value: 0x7f08003a
			public const int btn_reg_logout = 2131230778;
			
			// aapt resource value: 0x7f080001
			public const int editEmail = 2131230721;
			
			// aapt resource value: 0x7f08000a
			public const int editPassword = 2131230730;
			
			// aapt resource value: 0x7f080007
			public const int editText1 = 2131230727;
			
			// aapt resource value: 0x7f080011
			public const int getUserInfoButton = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int getUserInfoTextView = 2131230738;
			
			// aapt resource value: 0x7f080008
			public const int imgLogo = 2131230728;
			
			// aapt resource value: 0x7f080016
			public const int item_subtitle = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int item_title = 2131230743;
			
			// aapt resource value: 0x7f080039
			public const int lblDashboard = 2131230777;
			
			// aapt resource value: 0x7f080021
			public const int linearLayout1 = 2131230753;
			
			// aapt resource value: 0x7f08000e
			public const int loginButton = 2131230734;
			
			// aapt resource value: 0x7f080038
			public const int mLlayoutBottomButtons = 2131230776;
			
			// aapt resource value: 0x7f080018
			public const int main_profile_layout = 2131230744;
			
			// aapt resource value: 0x7f08003b
			public const int menu = 2131230779;
			
			// aapt resource value: 0x7f08001a
			public const int sample_content_fragment = 2131230746;
			
			// aapt resource value: 0x7f080013
			public const int sample_main_layout = 2131230739;
			
			// aapt resource value: 0x7f08000f
			public const int sayHelloWorldButton = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int sayHelloWorldTextView = 2131230736;
			
			// aapt resource value: 0x7f080020
			public const int scrollView1 = 2131230752;
			
			// aapt resource value: 0x7f080014
			public const int slidingTabs = 2131230740;
			
			// aapt resource value: 0x7f080005
			public const int sliding_tabs = 2131230725;
			
			// aapt resource value: 0x7f080027
			public const int spinner = 2131230759;
			
			// aapt resource value: 0x7f080023
			public const int tableLayout1 = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int tableRow1 = 2131230756;
			
			// aapt resource value: 0x7f080009
			public const int txtCaption = 2131230729;
			
			// aapt resource value: 0x7f080029
			public const int txtCity = 2131230761;
			
			// aapt resource value: 0x7f080036
			public const int txtConfirmPassword = 2131230774;
			
			// aapt resource value: 0x7f08002c
			public const int txtCountry = 2131230764;
			
			// aapt resource value: 0x7f080033
			public const int txtEmail = 2131230771;
			
			// aapt resource value: 0x7f080030
			public const int txtFirstName = 2131230768;
			
			// aapt resource value: 0x7f080000
			public const int txtForgotPw = 2131230720;
			
			// aapt resource value: 0x7f080032
			public const int txtLastName = 2131230770;
			
			// aapt resource value: 0x7f080031
			public const int txtMiddleName = 2131230769;
			
			// aapt resource value: 0x7f080019
			public const int txtMyProfile = 2131230745;
			
			// aapt resource value: 0x7f080035
			public const int txtPassword = 2131230773;
			
			// aapt resource value: 0x7f08002d
			public const int txtPhoneNumber = 2131230765;
			
			// aapt resource value: 0x7f08002a
			public const int txtState = 2131230762;
			
			// aapt resource value: 0x7f080028
			public const int txtStreetAddress = 2131230760;
			
			// aapt resource value: 0x7f080034
			public const int txtUsername = 2131230772;
			
			// aapt resource value: 0x7f08002b
			public const int txtZipcode = 2131230763;
			
			// aapt resource value: 0x7f08001c
			public const int txt_reg_email = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int txt_reg_password = 2131230749;
			
			// aapt resource value: 0x7f08001b
			public const int txt_reg_username = 2131230747;
			
			// aapt resource value: 0x7f080015
			public const int viewPager = 2131230741;
			
			// aapt resource value: 0x7f080006
			public const int viewpager = 2131230726;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ForgotPassword = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Forum = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FragmentSample = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int GroupsPage = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainScrollLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PagerItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ProfilePage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Register = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int RegisterAdditionalInfo = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int RegisterBasicInfo = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Storyboard = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int action_bar_main = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040005
			public const int ApplicationName = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int get_UserInfo = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int get_hello_world_data = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int login = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int month_prompt = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int say_hello_world = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CustomActionBarTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MyActionBar = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
