#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MentorJ.Android.Resource", IsApplication=true)]

namespace MentorJ.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int array_months = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BackgroundGradient = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonContinueStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ButtonLogInStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int EditTextStyle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int samplelogo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int SpinnerItem = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070021
			public const int AdditionalInfo = 2131165217;
			
			// aapt resource value: 0x7f07002e
			public const int BasicInfo = 2131165230;
			
			// aapt resource value: 0x7f070025
			public const int boxFemale = 2131165221;
			
			// aapt resource value: 0x7f070024
			public const int boxMale = 2131165220;
			
			// aapt resource value: 0x7f070036
			public const int btnContinue = 2131165238;
			
			// aapt resource value: 0x7f07002d
			public const int btnContinue2 = 2131165229;
			
			// aapt resource value: 0x7f07000c
			public const int btnForgotPw = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int btnLogin = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int btnRegister = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int btnReturn = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int btnSample = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int btnSend = 2131165186;
			
			// aapt resource value: 0x7f07001e
			public const int btn_reg_back = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int btn_reg_create = 2131165213;
			
			// aapt resource value: 0x7f070039
			public const int btn_reg_logout = 2131165241;
			
			// aapt resource value: 0x7f070001
			public const int editEmail = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int editPassword = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int editText1 = 2131165191;
			
			// aapt resource value: 0x7f070011
			public const int getUserInfoButton = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int getUserInfoTextView = 2131165202;
			
			// aapt resource value: 0x7f070008
			public const int imgLogo = 2131165192;
			
			// aapt resource value: 0x7f070016
			public const int item_subtitle = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int item_title = 2131165207;
			
			// aapt resource value: 0x7f070038
			public const int lblDashboard = 2131165240;
			
			// aapt resource value: 0x7f070020
			public const int linearLayout1 = 2131165216;
			
			// aapt resource value: 0x7f07000e
			public const int loginButton = 2131165198;
			
			// aapt resource value: 0x7f070037
			public const int mLlayoutBottomButtons = 2131165239;
			
			// aapt resource value: 0x7f070019
			public const int sample_content_fragment = 2131165209;
			
			// aapt resource value: 0x7f070013
			public const int sample_main_layout = 2131165203;
			
			// aapt resource value: 0x7f07000f
			public const int sayHelloWorldButton = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int sayHelloWorldTextView = 2131165200;
			
			// aapt resource value: 0x7f07001f
			public const int scrollView1 = 2131165215;
			
			// aapt resource value: 0x7f070014
			public const int slidingTabs = 2131165204;
			
			// aapt resource value: 0x7f070005
			public const int sliding_tabs = 2131165189;
			
			// aapt resource value: 0x7f070026
			public const int spinner = 2131165222;
			
			// aapt resource value: 0x7f070022
			public const int tableLayout1 = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int tableRow1 = 2131165219;
			
			// aapt resource value: 0x7f070009
			public const int txtCaption = 2131165193;
			
			// aapt resource value: 0x7f070028
			public const int txtCity = 2131165224;
			
			// aapt resource value: 0x7f070035
			public const int txtConfirmPassword = 2131165237;
			
			// aapt resource value: 0x7f07002b
			public const int txtCountry = 2131165227;
			
			// aapt resource value: 0x7f070032
			public const int txtEmail = 2131165234;
			
			// aapt resource value: 0x7f07002f
			public const int txtFirstName = 2131165231;
			
			// aapt resource value: 0x7f070000
			public const int txtForgotPw = 2131165184;
			
			// aapt resource value: 0x7f070031
			public const int txtLastName = 2131165233;
			
			// aapt resource value: 0x7f070030
			public const int txtMiddleName = 2131165232;
			
			// aapt resource value: 0x7f070018
			public const int txtMyProfile = 2131165208;
			
			// aapt resource value: 0x7f070034
			public const int txtPassword = 2131165236;
			
			// aapt resource value: 0x7f07002c
			public const int txtPhoneNumber = 2131165228;
			
			// aapt resource value: 0x7f070029
			public const int txtState = 2131165225;
			
			// aapt resource value: 0x7f070027
			public const int txtStreetAddress = 2131165223;
			
			// aapt resource value: 0x7f070033
			public const int txtUsername = 2131165235;
			
			// aapt resource value: 0x7f07002a
			public const int txtZipcode = 2131165226;
			
			// aapt resource value: 0x7f07001b
			public const int txt_reg_email = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int txt_reg_password = 2131165212;
			
			// aapt resource value: 0x7f07001a
			public const int txt_reg_username = 2131165210;
			
			// aapt resource value: 0x7f070015
			public const int viewPager = 2131165205;
			
			// aapt resource value: 0x7f070006
			public const int viewpager = 2131165190;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ForgotPassword = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Forum = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FragmentSample = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int GroupsPage = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainScrollLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PagerItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ProfilePage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Register = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int RegisterAdditionalInfo = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int RegisterBasicInfo = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Storyboard = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040005
			public const int ApplicationName = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int get_UserInfo = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int get_hello_world_data = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int login = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int month_prompt = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int say_hello_world = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CustomActionBarTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MyActionBar = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
