#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HelloWorld.Android.Resource", IsApplication=true)]

namespace HelloWorld.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int btn_reg_back = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int btn_reg_create = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int btn_reg_logout = 2131034128;
			
			// aapt resource value: 0x7f050006
			public const int btnlogin = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int btnregister = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int getHelloWorldDataButton = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int getHelloWorldDataTextView = 2131034115;
			
			// aapt resource value: 0x7f05000f
			public const int lblDashboard = 2131034127;
			
			// aapt resource value: 0x7f050008
			public const int loginButton = 2131034120;
			
			// aapt resource value: 0x7f05000e
			public const int mLlayoutBottomButtons = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int sayHelloWorldButton = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int sayHelloWorldTextView = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int txt_reg_email = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int txt_reg_password = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int txt_reg_username = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int txtpwd = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int txtusername = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HelloWorld = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Register = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Storyboard = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int get_hello_world_data = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int login = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int say_hello_world = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
